#spring.thymeleaf.check-template-location=false
server:
  port: 8082

spring:
#  profiles:
#    active: dev
#  application:
#    name: gateway
#  jackson:
#    serialization:
#      indent_output: true
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
#    prefix: /WEB-INF/templates/
    suffix: .html